# Generated by Django 2.2.2 on 2022-05-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20220526_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpost',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='demo/static/user_images'),
        ),
    ]
