# Generated by Django 4.0.4 on 2022-05-31 18:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20220526_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
